website/auth.py
import os
from .util import get_env_variables, get_testing_env_variables
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from .models import User, _str_uuid
from . import db
from flask_login import login_user, login_required, logout_user, current_user

#################################
from typing import Dict
import json
import requests
import base64
import secrets
#################################
auth = Blueprint("auth", __name__)


################
#
# 	Server	Configuration & Other Settings
#
################
env_vars = get_env_variables()
# mixpanel
from mixpanel import Mixpanel
mp = Mixpanel(env_vars["MIXPANEL_PROJECT_ID"])
# 	customers	domain
server_id = env_vars["SERVER_ID"]
# 	customer	origin	site
server_origin = env_vars["SERVER_ORIGIN"]
# origin	=	"https://bloc.id"
server_name = env_vars["SERVER_NAME"]

# 	A	simple	way	to	persist	challenges	until	response	verification
current_registration_challenge = None
current_authentication_challenge = None


################
#
# 	Registration
#
################
# email signup
@auth.route("/signup", methods=["GET", "POST"])
def signup_email():
    pricing_plan = ""
    # check for choice pricing plan
    if request.method == "POST":
        # if growth plan
        if request.form['price-plan-btn'] == "growth":
            pricing_plan = "growth"
            session["pricing_plan"] = pricing_plan
        # if enterprise
        elif request.form['price-plan-btn'] == "enterprise":
            pricing_plan = "enterprise"
            session["pricing_plan"] = pricing_plan
        # else is starter
        else:
            pricing_plan = "starter"
            session["pricing_plan"] = pricing_plan
            print(session["pricing_plan"])
    # else is starter
    if request.method == "GET":
        pricing_plan = "starter"
        session["pricing_plan"] = pricing_plan
        print(session["pricing_plan"])
    return render_template("app/auth/signup_email.html", user=current_user)


#####################
# 	signup view
@auth.route("/auth/signup", methods=["GET", "POST"])
def signup():
    if request.method == "POST":
        # generate uuid
        user_uid = _str_uuid()
        # add uuid to session
        session["user_uid"] = user_uid
        # check if uuid already exists
        user = User.query.filter_by(uid=session["user_uid"]).first()
        # if user uid already exists, generate a new uid
        if user:
            while user:
                user_uid = _str_uuid()
                # add uuid to session
                session["user_uid"] = user_uid
                # check if uuid already exists
                user = User.query.filter_by(uid=session["user_uid"]).first()
                print(f'Final uid: {session["user_id"]}')

        # add email to session
        session["email"] = request.form.get("email")
        # Retrieve the time zone value from the form data
        session["timezone"] = request.form.get('timezone')
        # 	check if user email already exists
        user = User.query.filter_by(email=session["email"]).first()
        if user:
            flash("Email	already	exists", category="error")
        elif len(session["email"]) < 4:
            flash("Email	must	be	longer	than	3	characters.", category="error")
        return redirect(url_for("auth.signup"))

    return render_template("app/auth/signup.html", user=current_user)


#####################
# generate registration options
@auth.route("/generate-registration-options", methods=["GET"])
def handler_generate_registration_options():
    global current_registration_challenge

    # payload
    payload = {
        "domain": server_id,
        "domain_name": server_name,
        "email": session["email"],
    }
    # recieve bloc api response
    response = requests.get(
        url="https://bloc-api.bloclabs.repl.co/bloc/users/signup", params=payload
    ).json()
    # json response to get registration challenge
    response_object = json.loads(response)
    # set registration challenge
    current_registration_challenge = response_object["challenge"]
    # decode registration challenge to future expected challenge
    current_registration_challenge = base64.urlsafe_b64decode(
        f"{current_registration_challenge}==="
    )
    # return response to bloc js package
    return response


#####################
# verify registration
@auth.route("/verify-registration-response", methods=["POST"])
def handler_verify_registration_response():
    body = request.get_data()
    print("BODY:	", type(body))
    payload = {
        "request": body,
        "domain": server_id,
        "domain_origin": server_origin,
        "email": session["email"],
        "pricing_plan": session["pricing_plan"],
        "user_api_key": session["user_uid"],
        "user_timezone" : session["timezone"]
    }
    # get response from post request and print it
    response = requests.post(
        url="https://bloc-api.bloclabs.repl.co/bloc/users/verify_signup", params=payload
    ).json()

    if response["verified"] == True:
        print(response)
        new_user = User(email=session["email"], pricing_plan=session["pricing_plan"], api_key=session["user_uid"])
        db.session.add(new_user)
        db.session.commit()
        # Note: you must supply the user_id who performed the event as the first parameter.
        login_user(new_user, remember=True)

        # tell mixpanel user is officially signed up
        mp.track(
            new_user.id,
            "Signed Up",
            {"Signup Type": "New User", "Username": new_user.email},
        )

        flash("Account created!", category="success")
        return response
    else:
        return {"verified": False}


################
#
# 	Authentication
#
################


# 	login email	view
@auth.route("/login", methods=["GET", "POST"])
def login_email():
    return render_template("app/auth/login_email.html", user=current_user)


# 	login	view
@auth.route("/auth/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        # get the users uid using the email
        session["email"] = request.form.get("email")
        print(session["email"])
        user = User.query.filter_by(email=session["email"]).first()
        if user:
            return redirect(url_for("auth.login"))
        else:
            flash("Email does not exist", category="error")
    return render_template("app/auth/login.html", user=current_user)


#####################
# generate authentication options
@auth.route("/generate-authentication-options", methods=["GET", "POST"])
def handler_generate_authentication_options():
    print("IN	GENERATE	AUTH	OPTIONS")
    global current_authentication_challenge

    payload = {
        "domain": server_id, 
        "email": session["email"]
        }
    # recieve bloc api response
    response = requests.get(
        url="https://bloc-api.bloclabs.repl.co/bloc/users/login", params=payload
    ).json()
    # json response to get registration challenge
    response_object = json.loads(response)
    # set registration challenge
    current_authentication_challenge = response_object["challenge"]
    # decode registration challenge to future expected challenge
    current_authentication_challenge = base64.urlsafe_b64decode(
        f"{current_authentication_challenge}==="
    )
    # return response to bloc js package
    return response


#####################
# verify authentication
@auth.route("/verify-authentication-response", methods=["POST"])
def hander_verify_authentication_response():
    print("IN	verify	AUTH	OPTIONS")
    global current_authentication_challenge

    body = request.get_data()

    payload = {
        "request": body,
        "domain": server_id,
        "domain_origin": server_origin,
        "email": session["email"],
    }
    print("response")
    # get response from post request and print it
    response = requests.post(
        url="https://bloc-api.bloclabs.repl.co/bloc/users/verify_login", params=payload
    ).json()

    """If user is verified """
    if response["verified"] == True:
        print(response)
        user = User.query.filter_by(email=session["email"]).first()
        login_user(user, remember=True)
        # tell mixpanel user is officially signed up
        mp.track(
            user.id,
            "Logged in",
            {"Login Type": "Existing User", "Username": user.email},
        )
        flash("Login successful!", category="success")
        return response
    else:
        return {"verified": False}


################
#
# 	Logout
#
################
@auth.route("/logout", methods=["GET", "POST"])
def logout():
    logout_user()
    return redirect(url_for("views.home"))

website/views.py
from flask import Blueprint, render_template, request, flash
from flask_login import login_required, current_user
from . import db

views = Blueprint('views', __name__)

################
#
#	App	Views
#
################
#	Home
@views.route("/",	methods=["GET",	"POST"])
def	home():
	return	render_template("app/home.html", user = current_user)

#	Pricing
@views.route("/pricing",	methods=["GET",	"POST"])
def	pricing():
	return	render_template("app/pricing.html", user = current_user)


################
#
#	Profile	Views
#
################
#	Setup
@views.route("/settings",	methods=["GET",	"POST"])
@login_required
def	settings():
	
	return	render_template("app/dashboard/profile/settings.html", user = current_user)

################
#
#	App	Docs	Views
#
################
# signup
@views.route("/docs/signup",	methods=["GET",	"POST"])
@login_required
def	docs_signup():
	return	render_template("app/dashboard/docs/signup.html", user = current_user)

# login
@views.route("/docs/login",	methods=["GET",	"POST"])
@login_required
def	docs_login():
	return	render_template("app/dashboard/docs/login.html", user = current_user)


################
#
#	App	Docs	Views
#
################
# signup
@views.route("quickstart/docs/signup")
def quick_docs_signup():
    return	render_template("app/docs_signup.html", user = current_user)


@views.route("quickstart/docs/login")
def quick_docs_login():
    return	render_template("app/docs_login.html", user = current_user)


################
#
#	Other	Views
#
################
@views.route("/debug",	methods=["GET",	"POST"])
def	debugging():
	return	render_template("demo-site/debug.html", user = current_user)

website/templates/app/docs_login.html
{% extends "app/dashboard/base.html" %} {% block title %}bloc | quick docs | login{% endblock title %}
{% block content %}
<!-- tracking page views -->
<script>
	// Send a default page view event with additional properties
	mixpanel.track_pageview({"page": "Quick Docs Login"});
</script>
<main>
  <!-- Start of Documentation -->
  <div class="bloc-doc-container p-2 container-fluid">
    <!-- Docs Header -->
    <center>
      <div class ="container pt-5">
        <h1> Login</h1>
        <p class="lead fw-normal text-muted mb-5 mb-lg-0">These docs made in a "start to finish" format to ensure success. It starts with <a class="lead fw-normal text-muted mb-5 mb-lg-0" href="/quickstart/docs/signup">Signup</a> then moves here to Login.</p>
		<p class="lead fw-normal text-muted mb-5 mb-lg-0">At any point that you need help, send a message in the chatbox, I'm happy to help!</p>
      </div>
    </center>
		<br>
    <!-- end Docs header -->
    <!--Login Docs-->
    <div class="container">
		<div class="alert alert-info" role="alert">
			<a class="nav-link me-lg-3" href="{{ url_for('auth.signup_email') }}">You can build without signing up, but api keys will be required to make requests. Click here to get an api key.</a>
		</div>
      <div>
		<center>
        <h2>Step 3: Server Login</h2>
        <img src="/static/app/images/finished-image.png" class="doc-img img-fluid p-3" alt="Goal">
          <p class="lead fw-normal text-muted mb-5 mb-lg-0">
            Step 3 completes the entire authentication process between device and your application
          </p>
        </center>
      </div>
	  <br>
      <div>
		<p class="lead fw-normal text-muted mb-5 mb-lg-0">
			Before login starting Copy the code below and place right before your &lt;/head&gt; on your login page that performs the device based authentication. You can try just inheriting from a template but at your discretion. There are no risks by doing it either way, just that it may not work with templating. That doen't mean it's impossible!
		</p>
		<br>
		<label for="quick-read" class="form-label"><strong>Skim Read:</strong></label>
		<ul>
			<li class=" pt-3 lead fw-normal text-muted mb-5 mb-lg-0">Copy and paste into login.html/respective file if your not using templates</li>
		</ul>
		<div class="bloc-code-box">
			<pre><code id="code-copied" class="language-javascript" data-prismjs-copy="Copy">
				&lt;script src="/your/static/folder/location/authn.min.js"&gt;&lt;/script&gt;
			</code></pre>
        </div>
				<!-- Start enable Send and Recieve DuoAuthn data -->
				<br>
				<p class="lead fw-normal text-muted mb-5 mb-lg-0">
					At this point you should be at "5. EDIT" out of 8 in your 'send and recieve data' js file. If you aren't go through the edits in the file to adjust to your application and the routes you've just built.
				</p>
        <!-- end Send and Recieve edit reminder -->
				<!-- Start Server Side -->
				<br>
				<h3>Login Flow</h3>
				<p class="lead fw-normal text-muted mb-5 mb-lg-0">
					Now, you'll be setting up the login flow. Exact same order of routes, recieving users email, proccesing users email, sending that users email to the api to initiate and verify the login authentication.
        </p>
				<br>
				<p class="lead fw-normal text-muted mb-5 mb-lg-0">
					The first route, recieving, is simply displaying a page with an input field like below.
        </p>
		<center>
				<img src="/static/app/images/login_email.jpg" class="doc-email-img img-fluid p-3" alt="Goal">
				<p class="lead fw-normal text-muted mb-5 mb-lg-0">
					This views server code is below
				</p>
			</center>
				<!-- building server email processing -->
				<p class="lead fw-normal text-muted mb-5 mb-lg-0">
					Now, build the proccesing route like below. This route is processing the email that will be submitted by your user. Make sure to redirect to this current route (this is important)
        </p>
		<br>
		<label for="quick-read" class="form-label"><strong>Skim Read:</strong></label>
		<ul>
			<li class=" pt-3 lead fw-normal text-muted mb-5 mb-lg-0">Copy and paste into auth.py/respective file</li>
		</ul>
        <div class="bloc-code-box">
          <pre><code class="language-python" data-prismjs-copy="Copy">if request.method == 'POST':
		# add email to your session
		session['email'] = request.form.get("name_of_your_login_input_field_here")
		# redirect to user next route to send to api (to this current route)
		return redirect(url_for('your.redirect_route_here'))</code></pre>
				</div>
				<!-- building login generation -->
				<p class="lead fw-normal text-muted mb-5 mb-lg-0">
					These next 2 parts are just like sign up. After you build this route, go into your 'auth-script' and do "6. EDIT".
					REMEMBER: All parameters must be in the SAME order as the code in the payload.
        </p>
		<br>
		<label for="quick-read" class="form-label"><strong>Skim Read:</strong></label>
		<ul>
			<li class=" pt-3 lead fw-normal text-muted mb-5 mb-lg-0">Copy and paste into auth.py/respective file</li>
		</ul>
        <div class="bloc-code-box">
          <pre><code class="language-python" data-prismjs-copy="Copy"># payload
	payload = {
		"api_key" : api_key,
		"domain" : rp_id, 
		"user_email" : session["email"],
	}
	# recieve bloc api response
	response = requests.get(url="https://bloc-api.bloclabs.repl.co/users/login", params=payload).json()
	# json response to get registration challenge 
	response_object = json.loads(response)
	# set registration challenge
	current_authentication_challenge = response_object["challenge"]
	# decode registration challenge to expected challenge (AGAIN the 3 ='s at the end are EXTREMELY IMPORTANT and NEED TO BE ADDED IN)
	current_authentication_challenge = base64.urlsafe_b64decode(f"{current_authentication_challenge}===")
	# return response to DuoAuthn js package, this is returning to '6. EDIT' if you cntl + f or command + f
	return response</code></pre>
				</div>
				<!-- building signup generation -->
				<p class="lead fw-normal text-muted mb-5 mb-lg-0">
					2nd part and lastly, login verification...
					then do "7. EDIT" and "8. EDIT".
        </p>
		<br>
		<center>
			<img src="/static/app/images/demo4.jpg" class="doc-email-img img-fluid p-3" alt="Goal">
			<p class="lead fw-normal text-muted mb-5 mb-lg-0">
				This views server code is below
			</p>
				</center>
		<br>
		<label for="quick-read" class="form-label"><strong>Skim Read:</strong></label>
		<ul>
			<li class=" pt-3 lead fw-normal text-muted mb-5 mb-lg-0">Copy and paste into auth.py/respective file</li>
		</ul>
        <div class="bloc-code-box">
          <pre><code class="language-python" data-prismjs-copy="Copy"># data from coming from DuoAuthn, '7. EDIT'
body	=	request.get_data()
# your payload for the api
payload = {
	"api_key" : api_key,
	"request" : body,
	"domain" : rp_id,
	"domain_origin" : origin,
	"user_email" : session["email"],
}
# recieve response from post request
response = requests.post(url="https://bloc-api.bloclabs.repl.co/users/verify_login", params= payload).json()
# if user is verified
if response["verified"] == True:
	# get user from your database
	user = YourUserModel.query.filter_by(email=session['email']).first()
	# login your user to your application
	# those who manually built their sessions, login user at this part of your authentication flow
	login_user(user,	remember=True)
	# flask feature to show user that they successfully logged in
	flash('Successfully logged in', category = 'success')
	# return this response to '7. EDIT'
	return response
# otherwise they won't be logged in
else:
	return {"verified":False}</code></pre>
				</div>
				<br>
				<center>
		      <div class ="container">
		        <h1> Congratulations yet again!!</h1>
				<center>
					<img src="/static/app/images/finished-image.png" class="doc-img img-fluid p-3" alt="Goal">
				</center>
		        <p class="lead fw-normal text-muted mb-lg-0">Your login is done, now go ahead and try out your new authentication system! It should call the device authentication like the image on the left above. Make sure you've signed up for an api key. That way when you click through, the device authenticator is called (TouchID/FaceID/Windows Hello prompt).</p>
				<p class="lead fw-normal text-muted mb-5 mb-lg-0">Something not working? Send a message in the chatbox, I'm happy to help!</p>
						<br>
		      </div>
		    </center>
				<!-- everything before the below div -->
      </div>
    </div>
  </div>
</main>
<!--===============================================================================================-->
<script src="static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
<script src="static/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
<script src="static/vendor/bootstrap/js/popper.js"></script>
<script src="static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
<script src="static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
<script src="static/vendor/daterangepicker/moment.min.js"></script>
<script src="static/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
<script src="static/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
<script src="static/js/main.js"></script>
<!-- JS -->
<script src="static/app/js/setup.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
  crossorigin="anonymous"></script>
{% endblock content %}

website/templates/app/pricing.html
{% extends "app/base.html" %} {% block title %}bloc | pricing{% endblock title
%} {% block content %}
<!-- mix panel-->
<script>
  // Send a default page view event with additional properties
  mixpanel.track_pageview({ page: "Pricing Page" });
</script>
<!-- Mashead header-->
<header class="pt-5 masthead">
  <div class="container px-4">
    <div class="row gx-5 align-items-center">
      <div class="price_plan_area section_padding_130_80" id="pricing">
        <div class="row justify-content-center">
          <div class="col-12 col-sm-8 col-lg-6">
            <!-- Section Heading-->
            <div
              class="section-heading text-center wow fadeInUp"
              data-wow-delay="0.2s"
              style="
                visibility: visible;
                animation-delay: 0.2s;
                animation-name: fadeInUp;
              "
            >
              <!-- <h6>Pricing Plans</h6> -->
              <h3>pricing</h3>
              <p>no credit card required to get started!</p>
              <br />
            </div>
          </div>
        </div>
        <div class="row justify-content-center">
          <!-- Starter Price Plan Area-->
          <div class="col-12 col-sm-8 col-md-6 col-lg-4">
            <div
              class="single_price_plan wow fadeInUp"
              data-wow-delay="0.2s"
              style="
                visibility: visible;
                animation-delay: 0.2s;
                animation-name: fadeInUp;
              "
            >
              <div class="title">
                <h3>Starter</h3>
                <p>for testing</p>
                <div class="line"></div>
              </div>
              <div class="price">
                <h4>Free!</h4>
                <p>get started fast</p>
              </div>
              <div class="description">
                <p><i class="lni lni-checkmark-circle"></i>20 Logins per month</p>
                <p>
                  <i class="lni lni-checkmark-circle"></i>Standard Customer
                  Support
                </p>
                <p hidden><i class="lni lni-checkmark-circle"></i>Remove Branding</p>
              </div>
              <!-- Starter plan form -->
              <form action="{{ url_for('auth.signup_email') }}" method="POST">
                <button class="btn starter-price-btn" id="starter-plan-signup-btn" name="price-plan-btn" type="submit" value="starter">Sign up</button>
              </form>
              <div hidden class="button" id="startup-plan-signup-btn">
                <a
                  class="btn starter-price-btn"
                  href="{{ url_for('auth.signup_email') }}"
                  >Sign up</a
                >
              </div>
              <!-- mix panel-->
              <script>
                // Send a default page view event with additional properties
                mixpanel.track_links(
                  "#starter-plan-signup-btn button",
                  {
                    "referrer": document.referrer,
                  }
                );
              </script>
            </div>
          </div>
          <!-- Growth Price Plan Area-->
          <div class="col-12 col-sm-8 col-md-6 col-lg-4">
            <div
              class="single_price_plan wow fadeInUp"
              data-wow-delay="0.2s"
              style="
                visibility: visible;
                animation-delay: 0.2s;
                animation-name: fadeInUp;
              "
            >
              <div class="title">
                <h3>Growth</h3>
                <p>for production</p>
                <div class="line"></div>
              </div>
              <div class="price">
                <h4>$0.10</h4>
                <p>per auth request</p>
              </div>
              <div class="description">
                <p><i class="lni lni-checkmark-circle"></i>Unlimited Logins</p>
                <p>
                  <i class="lni lni-checkmark-circle"></i>Premium Customer
                  Support
                </p>
                <p hidden ><i class="lni lni-checkmark-circle"></i>Remove Branding</p>
              </div>
              <!-- Growth plan form -->
              <form action="{{ url_for('auth.signup_email') }}" method="POST">
                <button class="btn startup-price-btn" id="growth-plan-signup-btn" name="price-plan-btn" type="submit" value="growth">Sign up</button>
              </form>
              <div hidden class="button" id="startup-plan-signup-btn">
                <a
                  class="btn startup-price-btn"
                  href="{{ url_for('auth.signup_email') }}"
                  >Sign up</a
                >
              </div>
              <!-- mix panel-->
              <script>
                // Send a default page view event with additional properties
                mixpanel.track_links(
                  "#growth-plan-signup-btn button",
                  {
                    "referrer": document.referrer,
                  }
                );
              </script>
            </div>
          </div>
          
          <!-- Small Business Price Plan Area--
                  <div class="col-12 col-sm-8 col-md-6 col-lg-4">
                     <div class="single_price_plan active wow fadeInUp" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: fadeInUp;">
                        <!-- Side Shape--
                        <div class="title">
                           <h3>small business</h3>
                           <p>for small business teams</p>
                           <div class="line"></div>
                        </div>
                        <div class="price">
                           <h4>$9.99</h4>
                        </div>
                        <div class="description">
                           <p><i class="lni lni-checkmark-circle"></i>Duration: 3 Month</p>
                           <p><i class="lni lni-checkmark-circle"></i>50 Features</p>
                           <p><i class="lni lni-checkmark-circle"></i>No Hidden Fees</p>
                           <p><i class="lni lni-checkmark-circle"></i>150+ Video Tuts</p>
                           <p><i class="lni lni-close"></i>5 Tools</p>
                        </div>
                        <div class="button"><a class="btn team-price-btn" href="#">Get Started</a></div>
                     </div>
                  </div> -->
          <!-- Enterprise Price Plan Area--
          <div class="col-12 col-sm-8 col-md-6 col-lg-4">
            <div
              class="single_price_plan wow fadeInUp"
              data-wow-delay="0.2s"
              style="
                visibility: visible;
                animation-delay: 0.2s;
                animation-name: fadeInUp;
              "
            >
              <div class="title">
                <h3>Enterprise</h3>
                <p>for later stage teams</p>
                <div class="line"></div>
              </div>
              <div class="price">
                <h4>Let's Chat</h4>
                <p>custom authentication</p>
              </div>
              <div class="description">
                <p>
                  <i class="lni lni-checkmark-circle"></i>Best for 10000+ users
                </p>
                <p><i class="lni lni-checkmark-circle"></i>Volume Discounts</p>
                <p>
                  <i class="lni lni-checkmark-circle"></i>Priority Customer
                  Service
                </p>
              </div>
              <!-- Enterprise plan form --
              <form action="{{ url_for('auth.signup_email') }}" method="POST">
                <button class="btn ent-price-btn" id="ent-plan-signup-btn" name="price-plan-btn" type="submit" value="enterprise">Sign up</button>
              </form>
              <div hidden class="button" id="ent-plan-signup-btn">
                <a
                  class="btn ent-price-btn"
                  href="{{ url_for('auth.signup_email') }}"
                  >Sign up</a 
                >
              </div> -->
              <!-- mix panel-->
              <script>
                // Send a default page view event with additional properties
                mixpanel.track_links(
                  "#ent-plan-signup-btn button",
                  {
                    "referrer": document.referrer,
                  }
                );
              </script>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock content %}

website/templates/app/signupsuccess.html
{% extends "account/index.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block head_title %}{% trans "Signup" %}{% endblock %}
{% block content %}
<form class="signup" id="signup_form" method="post" action="{% url 'account_logout' %}">
   {% csrf_token %}
   <center><img src="/static/images/birds.svg" alt="bloc" width="95" height="84" class="logo d-inline-block align-text-top"></center>
   <span class="login100-form-title pb-3 signup-success-span">
   sign up successful!
   </span>
   <center>
      <strong>
          <small>Thank you for your interest, your spot in line has been reserved!</small>
      </strong>
   </center>
   <br>
   <div class="container-login100-form-btn">
    <div class="wrap-login100-form-btn">
       <div class="login100-form-bgbtn"></div>
       <button class="login100-form-btn" type = "submit">
        {% trans "return home" %} &raquo;
       </button>
    </div>
   </div>
</form>
{% endblock %}