website/auth.py
import os
from .util import get_env_variables, get_testing_env_variables
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from .models import User, _str_uuid
from . import db
from flask_login import login_user, login_required, logout_user, current_user

#################################
from typing import Dict
import json
import requests
import base64
import secrets
#################################
auth = Blueprint("auth", __name__)


################
#
# 	Server	Configuration & Other Settings
#
################
env_vars = get_env_variables()
# mixpanel
from mixpanel import Mixpanel
mp = Mixpanel(env_vars["MIXPANEL_PROJECT_ID"])
# 	customers	domain
server_id = env_vars["SERVER_ID"]
# 	customer	origin	site
server_origin = env_vars["SERVER_ORIGIN"]
# origin	=	"https://bloc.id"
server_name = env_vars["SERVER_NAME"]

# 	A	simple	way	to	persist	challenges	until	response	verification
current_registration_challenge = None
current_authentication_challenge = None


################
#
# 	Registration
#
################
# email signup
@auth.route("/signup", methods=["GET", "POST"])
def signup_email():
    pricing_plan = ""
    # check for choice pricing plan
    if request.method == "POST":
        # if growth plan
        if request.form['price-plan-btn'] == "growth":
            pricing_plan = "growth"
            session["pricing_plan"] = pricing_plan
        # if enterprise
        elif request.form['price-plan-btn'] == "enterprise":
            pricing_plan = "enterprise"
            session["pricing_plan"] = pricing_plan
        # else is starter
        else:
            pricing_plan = "starter"
            session["pricing_plan"] = pricing_plan
            print(session["pricing_plan"])
    # else is starter
    if request.method == "GET":
        pricing_plan = "starter"
        session["pricing_plan"] = pricing_plan
        print(session["pricing_plan"])
    return render_template("app/auth/signup_email.html", user=current_user)


#####################
# 	signup view
@auth.route("/auth/signup", methods=["GET", "POST"])
def signup():
    if request.method == "POST":
        # generate uuid
        user_uid = _str_uuid()
        # add uuid to session
        session["user_uid"] = user_uid
        # check if uuid already exists
        user = User.query.filter_by(uid=session["user_uid"]).first()
        # if user uid already exists, generate a new uid
        if user:
            while user:
                user_uid = _str_uuid()
                # add uuid to session
                session["user_uid"] = user_uid
                # check if uuid already exists
                user = User.query.filter_by(uid=session["user_uid"]).first()
                print(f'Final uid: {session["user_id"]}')

        # add email to session
        session["email"] = request.form.get("email")
        # Retrieve the time zone value from the form data
        session["timezone"] = request.form.get('timezone')
        # 	check if user email already exists
        user = User.query.filter_by(email=session["email"]).first()
        if user:
            flash("Email	already	exists", category="error")
        elif len(session["email"]) < 4:
            flash("Email	must	be	longer	than	3	characters.", category="error")
        return redirect(url_for("auth.signup"))

    return render_template("app/auth/signup.html", user=current_user)


#####################
# generate registration options
@auth.route("/generate-registration-options", methods=["GET"])
def handler_generate_registration_options():
    global current_registration_challenge

    # payload
    payload = {
        "domain": server_id,
        "domain_name": server_name,
        "email": session["email"],
    }
    # recieve bloc api response
    response = requests.get(
        url="https://bloc-api.bloclabs.repl.co/bloc/users/signup", params=payload
    ).json()
    # json response to get registration challenge
    response_object = json.loads(response)
    # set registration challenge
    current_registration_challenge = response_object["challenge"]
    # decode registration challenge to future expected challenge
    current_registration_challenge = base64.urlsafe_b64decode(
        f"{current_registration_challenge}==="
    )
    # return response to bloc js package
    return response


#####################
# verify registration
@auth.route("/verify-registration-response", methods=["POST"])
def handler_verify_registration_response():
    body = request.get_data()
    print("BODY:	", type(body))
    payload = {
        "request": body,
        "domain": server_id,
        "domain_origin": server_origin,
        "email": session["email"],
        "pricing_plan": session["pricing_plan"],
        "user_api_key": session["user_uid"],
        "user_timezone" : session["timezone"]
    }
    # get response from post request and print it
    response = requests.post(
        url="https://bloc-api.bloclabs.repl.co/bloc/users/verify_signup", params=payload
    ).json()

    if response["verified"] == True:
        print(response)
        new_user = User(email=session["email"], pricing_plan=session["pricing_plan"], api_key=session["user_uid"])
        db.session.add(new_user)
        db.session.commit()
        # Note: you must supply the user_id who performed the event as the first parameter.
        login_user(new_user, remember=True)

        # tell mixpanel user is officially signed up
        mp.track(
            new_user.id,
            "Signed Up",
            {"Signup Type": "New User", "Username": new_user.email},
        )

        flash("Account created!", category="success")
        return response
    else:
        return {"verified": False}


################
#
# 	Authentication
#
################


# 	login email	view
@auth.route("/login", methods=["GET", "POST"])
def login_email():
    return render_template("app/auth/login_email.html", user=current_user)


# 	login	view
@auth.route("/auth/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        # get the users uid using the email
        session["email"] = request.form.get("email")
        print(session["email"])
        user = User.query.filter_by(email=session["email"]).first()
        if user:
            return redirect(url_for("auth.login"))
        else:
            flash("Email does not exist", category="error")
    return render_template("app/auth/login.html", user=current_user)


#####################
# generate authentication options
@auth.route("/generate-authentication-options", methods=["GET", "POST"])
def handler_generate_authentication_options():
    print("IN	GENERATE	AUTH	OPTIONS")
    global current_authentication_challenge

    payload = {
        "domain": server_id, 
        "email": session["email"]
        }
    # recieve bloc api response
    response = requests.get(
        url="https://bloc-api.bloclabs.repl.co/bloc/users/login", params=payload
    ).json()
    # json response to get registration challenge
    response_object = json.loads(response)
    # set registration challenge
    current_authentication_challenge = response_object["challenge"]
    # decode registration challenge to future expected challenge
    current_authentication_challenge = base64.urlsafe_b64decode(
        f"{current_authentication_challenge}==="
    )
    # return response to bloc js package
    return response


#####################
# verify authentication
@auth.route("/verify-authentication-response", methods=["POST"])
def hander_verify_authentication_response():
    print("IN	verify	AUTH	OPTIONS")
    global current_authentication_challenge

    body = request.get_data()

    payload = {
        "request": body,
        "domain": server_id,
        "domain_origin": server_origin,
        "email": session["email"],
    }
    print("response")
    # get response from post request and print it
    response = requests.post(
        url="https://bloc-api.bloclabs.repl.co/bloc/users/verify_login", params=payload
    ).json()

    """If user is verified """
    if response["verified"] == True:
        print(response)
        user = User.query.filter_by(email=session["email"]).first()
        login_user(user, remember=True)
        # tell mixpanel user is officially signed up
        mp.track(
            user.id,
            "Logged in",
            {"Login Type": "Existing User", "Username": user.email},
        )
        flash("Login successful!", category="success")
        return response
    else:
        return {"verified": False}


################
#
# 	Logout
#
################
@auth.route("/logout", methods=["GET", "POST"])
def logout():
    logout_user()
    return redirect(url_for("views.home"))

website/views.py
from flask import Blueprint, render_template, request, flash
from flask_login import login_required, current_user
from . import db

views = Blueprint('views', __name__)

################
#
#	App	Views
#
################
#	Home
@views.route("/",	methods=["GET",	"POST"])
def	home():
	return	render_template("app/home.html", user = current_user)

#	Pricing
@views.route("/pricing",	methods=["GET",	"POST"])
def	pricing():
	return	render_template("app/pricing.html", user = current_user)


################
#
#	Profile	Views
#
################
#	Setup
@views.route("/settings",	methods=["GET",	"POST"])
@login_required
def	settings():
	
	return	render_template("app/dashboard/profile/settings.html", user = current_user)

################
#
#	App	Docs	Views
#
################
# signup
@views.route("/docs/signup",	methods=["GET",	"POST"])
@login_required
def	docs_signup():
	return	render_template("app/dashboard/docs/signup.html", user = current_user)

# login
@views.route("/docs/login",	methods=["GET",	"POST"])
@login_required
def	docs_login():
	return	render_template("app/dashboard/docs/login.html", user = current_user)


################
#
#	App	Docs	Views
#
################
# signup
@views.route("quickstart/docs/signup")
def quick_docs_signup():
    return	render_template("app/docs_signup.html", user = current_user)


@views.route("quickstart/docs/login")
def quick_docs_login():
    return	render_template("app/docs_login.html", user = current_user)


################
#
#	Other	Views
#
################
@views.route("/debug",	methods=["GET",	"POST"])
def	debugging():
	return	render_template("demo-site/debug.html", user = current_user)

website/templates/archives/app/dashboard/base.html
<!doctype html>
<html lang="en">
  <head>
    <title>{%block title %}{% endblock title %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->	
    <link rel="icon" type="image/png" href="/static/app/favicon.ico"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/static/app/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/static/app/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/static/app/fonts/iconic/css/material-design-iconic-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/static/app/vendor/animate/animate.css">
    <!--===============================================================================================-->	
    <link rel="stylesheet" type="text/css" href="/static/app/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/static/app/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/static/app/vendor/select2/select2.min.css">
    <!--===============================================================================================-->	
    <link rel="stylesheet" type="text/css" href="/static/app/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/static/app/css/util.css">
    <link rel="stylesheet" type="text/css" href="/static/app/css/main.css">
    <link rel="stylesheet" type="text/css" href="/static/app/css/setup.css">
		<link rel="stylesheet" type="text/css" href="/static/app/css/styles.css">
    <!--===============================================================================================-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
		
  </head>
  <body>
    <!-- nav bar -->
    <nav class="navbar navbar-expand-lg navbar-light shadow-sm" id = "mainNav" >
      <div class="container">
        <a class="navbar-brand fw-bold" href="{{ url_for('views.dash_home') }}">
        <img src="/static/images/blocImproved.svg" alt="bloc" width="110" height="99" class="logo d-inline-block align-text-top">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="bi-list"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          {% if user.is_authenticated %}
          <ul class="navbar-nav ms-auto me-4 my-3 my-lg-0">
            <li class="nav-item"><a class="nav-link me-lg-3" href="#Authenticated">{{ user.email }}</a></li>
						<li class="nav-item"><a class="nav-link me-lg-3" href="{{ url_for('views.dash_home') }}">home</a></li>
						<li class="nav-item"><a class="nav-link me-lg-3" href="/#features">payments</a></li>
            <li class="nav-item"><a class="nav-link me-lg-3" href="/#features">settings</a></li>
            <li class="nav-item"><a class="nav-link me-lg-3" href="{{ url_for('views.pricing') }}">support</a></li>
            <li class="nav-item"><a class="nav-link me-lg-3" href = "{{ url_for('auth.logout') }}">logout</a></li>
          </ul>
          {% else %}
          <ul class="navbar-nav ms-auto me-4 my-3 my-lg-0">
					 	<li class="nav-item"><a class="nav-link me-lg-3" href = "{{ url_for('auth.logout') }}">johndoe@email.com</a></li>
          </ul>
          {% endif %}
        </div>
      </div>
    </nav>
    <!-- Main content-->
      {% block content %}
      {% endblock content %}
    <!-- Footer-->
    <!--===============================================================================================-->
    <script src="/static/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="/static/vendor/animsition/js/animsition.min.js"></script>
    <!--===============================================================================================-->
    <script src="/static/vendor/bootstrap/js/popper.js"></script>
    <script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="/static/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="/static/vendor/daterangepicker/moment.min.js"></script>
    <script src="/static/vendor/daterangepicker/daterangepicker.js"></script>
    <!--===============================================================================================-->
    <script src="/static/vendor/countdowntime/countdowntime.js"></script>
    <!--===============================================================================================-->
    <script src="/static/js/main.js"></script>
    <!-- JS -->
    <script src="/static/app/js/setup.js"></script>
		<script src="/static/js/util.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"></script>
  </body>
</html>

website/templates/archives/app/dashboard/home.html
{% extends "app/dashboard/base.html" %} {% block title %}dash | home{% endblock title %}
{% block content %}
<main class = "dash-container">
  <div class = "container dash-container">
    <!-- Set Field -->
    <div class = "container limiter">
      <div class="mb-3">
        <span class="login100-form-title p-5 container-lg">
          <h3 class = "company-name">Auth Status</h3>
          <h4 class = "OK">OK</h4>
        </span>
      </div>
      <!-- Set brand colors -->
      <span class="login100-form-title p-5 container-lg">
        <h3 class = "company-name">Successful Logins</h3>
        <h4 class = "succ-logins">0</h4>
      </span>
      <!-- line break -->
      <br>
      <!-- Set logo -->
      <!-- Submit button -->
      <h4>Make changes?</h4>
      <button type="button" class=" btn btn-primary btn-submit">Edit</button>
    </div>
    <!-- Break -->
  </div>
  <!-- User Created Template -->
  <div class="limiter">
    <div class="container-login100">
      <div class="wrap-login100">
        <form method = "POST" action = "#" class="login100-form validate-form">
          <span class="login100-form-title py-5 px-5 container-xl" id = "display_image">
            <h3 class = "company-name">Your Brand</h3>
          </span>
          <span class="login100-form-title p-b-48">
            <p class = "setup-signup-header-message">Enter your email below to sign up for an example account</p>
          </span>
          <div class="wrap-input100 validate-input" data-validate = "Valid email is: a@b.c">
            <label class = "field-name">Email</label>
            <strong><input class="input100" type="text" name="username" id="username" placeholder = "Enter email"></strong>
            <span class="focus-input100"></span>
          </div>
          <div class="container-login100-form-btn">
            <div class="wrap-login100-form-btn">
              <div class="login100-form-bgbtn"></div>
              <button class="login100-form-btn">
              Sign up
              </button>
            </div>
          </div>
          <div hidden class="text-center p-t-115">
            <span class="txt1">
            Already have an account?
            </span>
            <br>
            <a class="txt2" href="#">
            Login
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div id="dropDownSelect1"></div>
  </div>
</main>
<!--===============================================================================================-->
<script src="static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
<script src="static/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
<script src="static/vendor/bootstrap/js/popper.js"></script>
<script src="static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
<script src="static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
<script src="static/vendor/daterangepicker/moment.min.js"></script>
<script src="static/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
<script src="static/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
<script src="static/js/main.js"></script>
<!-- JS -->
<script src="static/app/js/setup.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
  crossorigin="anonymous"></script>
{% endblock content %}